import { extraScenarioItems, extraWorkStyleItems } from './assessment-extra'

export type WorkStyleItem = {
  id: string
  type: 'workstyle-pair'
  left: string
  right: string
  dimension: 'customer' | 'ownership' | 'learning' | 'quality' | 'action' | 'trust'
  note: string
}

export type ScenarioOption = { id: string; text: string; score: 0 | 1 | 2 | 3; rationale: string }
export type ScenarioItem = {
  id: string
  type: 'scenario-choice'
  title: string
  situation: string
  options: ScenarioOption[]
  principle: string
}

const baseWorkStyleItems: WorkStyleItem[] = [
  ['action','I prefer to wait until I have every detail before acting.','I make a reversible decision with the best information available and adjust when needed.','Consider how you balance speed with evidence.'],
  ['ownership','If a customer issue crosses team boundaries, I stay involved until the handoff is genuinely complete.','Once I transfer the case to the correct team, my responsibility is finished.','Think about end-to-end ownership without ignoring role boundaries.'],
  ['learning','I would rather keep a process unchanged if it usually works.','I look for recurring friction and suggest a simpler process when evidence supports it.','Improvement should be grounded in facts and customer impact.'],
  ['customer','Meeting a speed target is more important than spending extra time on a difficult customer.','I protect customer resolution while still looking for an efficient way to handle the case.','Strong service balances quality and efficiency rather than treating them as opposites.'],
  ['ownership','If I make a mistake, I fix the immediate problem and move on.','I fix it, own it, and look for a way to prevent the same issue recurring.','Ownership includes recovery, prevention and learning.'],
  ['quality','When a policy seems unclear, I give the customer my best guess so they are not kept waiting.','I verify the policy or escalate appropriately before making a promise I may not be able to keep.','Accuracy and expectation-setting protect trust.'],
  ['learning','I am comfortable receiving direct feedback when it helps me improve.','I prefer to work independently without much feedback once I know the basics.','Choose what genuinely reflects how you work; consistency matters more than gaming a profile.'],
  ['trust','If I disagree with a teammate, I explain my evidence respectfully and then support the final decision.','I avoid disagreement because it can damage working relationships.','Professional disagreement can coexist with trust.'],
  ['customer','I focus mainly on the metric I am personally measured on.','I consider my metric alongside the wider customer and team outcome.','Good judgment considers the whole system, not one number.'],
  ['action','When volume suddenly spikes, I keep working in the same order as usual.','I reprioritize based on urgency, customer impact, and what can safely wait.','Prioritization should react to risk and impact.'],
  ['quality','I prefer to double-check high-risk actions even if it takes a little longer.','Speed matters so much that I avoid checking work unless something looks obviously wrong.','Think about when verification prevents bigger downstream problems.'],
  ['trust','If I am unsure, I ask a focused question early rather than hide the uncertainty.','I avoid asking questions because I do not want to appear inexperienced.','Trust grows when uncertainty is handled transparently and efficiently.'],
  ['customer','If policy prevents the customer’s preferred outcome, I explain the reason and look for the best valid alternative.','If policy prevents what they want, there is little value in discussing alternatives.','Customer focus continues even when the ideal outcome is unavailable.'],
  ['action','When several tasks are urgent, I identify risk and dependencies before deciding the order.','When several tasks are urgent, I simply do whichever arrived first.','Urgency, harm and dependencies may matter more than FIFO.'],
  ['learning','After a difficult interaction, I think about what I could improve next time.','Once a difficult interaction is finished, I prefer not to revisit it.','Reflection turns one case into reusable learning.'],
  ['ownership','If a handoff is necessary, I include enough context so the customer does not have to start over.','The next team can gather the context themselves after the transfer.','A quality handoff reduces customer effort and repeat explanation.'],
  ['quality','I document important details while they are fresh, even on a busy day.','Documentation can wait until volume is low because serving the next customer is always more important.','Good notes reduce repeat work and errors.'],
  ['trust','I would rather say “I need to verify that” than sound certain about something I am not sure of.','Customers are more confident when the agent always sounds certain.','Credibility comes from accurate confidence, not bluffing.'],
  ['customer','I try to understand the practical impact on the customer before deciding how urgent an issue is.','All issues in the same queue should be treated as equally urgent.','Customer impact helps determine priority.'],
  ['learning','If a new tool is introduced, I experiment with it and ask questions until I understand it.','I prefer to keep using the old method as long as it still works.','Adaptability matters when tools and processes change.'],
  ['action','I am comfortable taking a safe next step when the decision can be reversed.','I prefer to escalate even small reversible decisions to avoid any chance of being wrong.','Bias for action still requires judgment about reversibility and risk.'],
  ['ownership','If I notice a recurring customer problem outside my immediate task, I surface it through the right channel.','I focus only on the case in front of me because broader process issues belong to someone else.','Ownership includes noticing patterns and routing them effectively.'],
  ['quality','If I discover conflicting information in two internal sources, I verify which source is current before advising the customer.','I use whichever source is easier to access so I can answer quickly.','Conflicting information should trigger verification.'],
  ['trust','I give a teammate specific feedback about the work, not about their personality.','I avoid giving feedback unless a manager asks me to.','Specific, respectful feedback supports trust and standards.'],
].map((x, i) => ({ id: `ws-${i + 1}`, type: 'workstyle-pair' as const, dimension: x[0] as WorkStyleItem['dimension'], left: x[1], right: x[2], note: x[3] }))

function scenario(id: number, title: string, principle: string, situation: string, strong: string, reasonable: string, weak: string, risky: string, strongWhy: string): ScenarioItem {
  const options: ScenarioOption[] = [
    { id: 'a', score: 3, text: strong, rationale: strongWhy },
    { id: 'b', score: 2, text: reasonable, rationale: `This is directionally useful, but “${reasonable}” is incomplete for ${principle.toLowerCase()}: it leaves an important part of verification, ownership, expectation-setting, or follow-through unresolved.` },
    { id: 'c', score: 1, text: weak, rationale: `“${weak}” addresses only part of the situation and does not adequately protect the ${principle.toLowerCase()} considerations that make this case difficult.` },
    { id: 'd', score: 0, text: risky, rationale: `“${risky}” is high-risk in this situation because it can create an unsupported promise, policy/security exposure, or a failure of ownership under ${principle.toLowerCase()}.` },
  ]
  const shift = id % 4
  const rotated = [...options.slice(shift), ...options.slice(0, shift)]
  return { id: `sj-${id}`, type: 'scenario-choice', title, principle, situation, options: rotated.map((o, idx) => ({ ...o, id: String.fromCharCode(97 + idx) })) }
}

const baseScenarioItems: ScenarioItem[] = [
  scenario(1,'Late delivery before an event','Customer focus + ownership','A customer says a delayed package is a birthday gift needed tomorrow. Tracking has not updated for two days. What is the best first response?','Acknowledge the impact, verify tracking and the valid delivery/replacement/refund options, then set a clear next step and expectation.','Check the tracking and tell the customer what it currently shows, then ask them to contact you again if nothing changes.','Explain that delays happen and ask them to wait another 48 hours.','Promise the package will arrive tomorrow so the customer feels reassured.','It combines empathy, facts, available options and ownership without inventing a promise.'),
  scenario(2,'Refund outside policy','Judgment + trust','A customer requests a refund that appears outside the normal policy and says another agent promised it. What should you do?','Review the account and prior contact notes, explain what you can verify, then use the correct exception or escalation path if appropriate.','Explain the normal policy and offer the closest valid alternative without checking the prior contact.','Repeat the policy until the customer accepts it.','Issue the refund immediately even if you do not have authority because retention is more important than policy.','It investigates the claimed promise before deciding and protects both trust and policy boundaries.'),
  scenario(3,'Security issue in a busy queue','Prioritization + risk','You have a possible account-security issue, a routine return, and a delivery-status question waiting. What should you prioritize?','Handle the possible security issue first, then rank the remaining cases by urgency and SLA.','Take the oldest case first but quickly flag the security case for review.','Take the easiest case first to improve throughput.','Leave all three untouched until a lead tells you what to do.','Potential security harm has a higher risk profile than routine service questions.'),
  scenario(4,'Abusive customer','Empathy + boundaries','A frustrated customer starts using personal insults while you are trying to resolve the issue. What is the strongest response?','Stay calm, acknowledge the underlying issue, set a respectful boundary, continue helping if possible, and follow escalation/safety policy if abuse continues.','Ignore the insults and continue helping without setting any boundary.','End the contact immediately after the first insult without explaining the boundary.','Respond in the same tone so the customer understands how they sound.','It protects professionalism, safety and the chance of resolution at the same time.'),
  scenario(5,'System outage','Communication + ownership','A required internal system goes down while a customer is waiting and you cannot complete the action immediately.','Explain the limitation plainly, capture what is needed, offer the available next step, and set a realistic follow-up expectation.','Tell the customer about the outage and ask them to contact again later.','Keep the customer on hold indefinitely until the system returns.','Pretend the request was completed and fix it later if the system comes back.','It is transparent about constraints while still reducing customer effort and preserving ownership.'),
  scenario(6,'Third contact for same issue','Dive deep + ownership','A customer says this is their third contact about the same unresolved issue.','Read prior notes, summarize your understanding, identify why previous steps failed, own the next action, and make any handoff or follow-up explicit.','Apologize and repeat the previous troubleshooting once more in case it works this time.','Ask the customer to explain everything again from the beginning.','Transfer them immediately because previous agents could not solve it.','It uses available history, finds the failure point and avoids forcing the customer to restart.'),
  scenario(7,'Damaged item with unclear photo','Facts + customer effort','A customer reports a damaged item. The uploaded photo is blurry and you cannot verify the damage clearly.','Acknowledge the issue, explain exactly what evidence is missing, ask for the minimum additional proof needed, and explain what happens next.','Ask for several new photos from every angle just to be safe.','Reject the claim because the existing image is not clear.','Approve any requested outcome without checking what the policy requires.','It minimizes customer effort while gathering only the evidence needed to make a sound decision.'),
  scenario(8,'Wrong item received','Resolution + prevention','A customer ordered one product but received another. The correct item is still in stock.','Verify the order, arrange the valid correction path, explain return requirements if any, and set clear expectations for the replacement.','Start a return and tell the customer to reorder the product themselves.','Apologize but only provide the return instructions.','Tell the customer to keep the wrong item and promise a free replacement regardless of policy.','It corrects the error while reducing customer effort and setting accurate expectations.'),
  scenario(9,'Customer wants a supervisor immediately','De-escalation + escalation','A customer opens the contact by demanding a supervisor and refuses to explain the issue.','Acknowledge the request, briefly ask what happened so you can route or resolve appropriately, and honor the escalation path if they still want it.','Try to solve the issue yourself and delay escalation until you have exhausted every option.','Tell them supervisors do not take calls unless you approve it.','Transfer blindly without any context or documentation.','It respects the request while gathering enough context for a useful resolution or handoff.'),
  scenario(10,'Potential duplicate charge','Financial risk + verification','A customer says they were charged twice for one order. One charge may be a temporary authorization.','Verify the transaction details and explain the difference between a posted charge and temporary authorization before deciding the next step.','Tell the customer to wait several days because duplicate charges often disappear.','Refund one charge immediately without checking whether both actually posted.','Tell the customer to dispute both charges with their bank first.','It verifies the financial facts before creating another transaction or sending the customer elsewhere.'),
  scenario(11,'Address change after shipment','Expectation setting','A customer wants to change the delivery address after the package has already shipped.','Check what changes are still possible at this shipment stage, explain the limits clearly, and offer the safest valid alternative.','Tell them to contact the carrier directly without checking what support can do.','Promise the address can be changed because the package has not arrived yet.','Cancel the entire order without customer approval.','It avoids false promises and gives the customer the best valid next step based on the shipment state.'),
  scenario(12,'Return without packaging','Policy + alternatives','A customer wants to return an item but no longer has the original packaging.','Check the actual return requirements for that item and explain the available return method rather than assuming packaging is mandatory.','Tell them original packaging is always required.','Approve the return but do not explain how to package it safely.','Tell them to send the item however they want and mark it returned in advance.','It verifies the actual rule and gives practical instructions instead of relying on assumptions.'),
  scenario(13,'Conflicting internal information','Quality + trust','Two internal knowledge pages give different instructions for the same customer issue.','Pause the unsupported advice, verify which source is current or escalate the conflict, then give the customer one accurate answer.','Choose the newer-looking page and proceed without verification.','Use whichever instruction is easier to explain.','Give the customer both versions and ask them to choose.','It treats conflicting policy as a quality risk and resolves the source of truth before advising the customer.'),
  scenario(14,'Customer asks for impossible guarantee','Trust + expectations','A customer asks you to guarantee that a replacement will arrive before an important trip.','Explain what delivery estimate you can verify, avoid guaranteeing what you cannot control, and discuss available alternatives if timing is critical.','Say it should probably arrive in time and hope the estimate holds.','Repeat the estimated date without acknowledging the importance of the trip.','Guarantee arrival because the customer says they will cancel otherwise.','It preserves trust by separating an estimate from a guarantee while still helping with the real need.'),
  scenario(15,'High-value order marked delivered','Risk + investigation','A high-value order is marked delivered, but the customer says they never received it.','Verify delivery details and account history, follow the correct missing-delivery investigation path, and explain the next milestone and timeline.','Refund immediately because the item is expensive.','Tell the customer tracking says delivered so there is nothing more to do.','Ask them to keep contacting the carrier until they find it.','It treats the case as higher risk, checks facts, and follows the right investigation path without abandoning the customer.'),
  scenario(16,'Language misunderstanding','Communication + empathy','A customer seems confused by your explanation and keeps answering a different question.','Slow down, use simpler wording, confirm understanding with one question at a time, and use any supported language/accessibility options if available.','Repeat the same explanation more loudly and slowly.','Send a long policy paragraph so the customer can read it themselves.','End the contact because communication is taking too long.','It adapts communication rather than blaming the customer for the misunderstanding.'),
  scenario(17,'Promotion not applied','Facts + fairness','A customer expected a promotion, but the discount did not apply at checkout.','Check the promotion terms, timing and eligibility, explain the exact reason, and use the valid correction or alternative if the conditions were met.','Apply the discount manually without checking eligibility.','Tell the customer promotions sometimes fail and nothing can be done.','Blame the website and promise a future credit you cannot authorize.','It distinguishes a genuine system error from ineligible use and responds fairly based on verified terms.'),
  scenario(18,'Customer threatens bad review','Judgment + composure','A customer says they will post a negative review unless you provide an exception you are not authorized to grant.','Stay focused on the issue, explain what you can do, use the correct escalation route for any exception, and do not trade unauthorized benefits for a review.','Offer a small unauthorized credit to prevent the negative review.','Tell them reviews do not matter and repeat the policy.','Argue that threatening a review is unfair and end the chat.','It separates reputation pressure from the decision and stays within authority while still looking for a valid resolution.'),
  scenario(19,'Possible fraud indicators','Security + escalation','A customer asks to change account details while several pieces of verification information do not match.','Stop sensitive changes, follow the identity/security verification process, and escalate according to the risk procedure.','Make the change if they can answer one basic question correctly.','Tell them exactly which security answers were wrong so they can try again.','Bypass verification because they sound genuinely upset.','It protects account security and avoids revealing verification details that could help an attacker.'),
  scenario(20,'Backlog and SLA risk','Prioritization + communication','You notice several customer cases are likely to miss SLA because volume is unusually high.','Prioritize by risk and customer impact, work the queue efficiently, and surface the capacity/SLA risk early through the right channel.','Work faster without telling anyone until the SLA is actually missed.','Handle only the easiest cases to reduce queue count.','Stop taking new work until a manager notices the backlog.','It combines immediate prioritization with early visibility of a systemic risk.'),
  scenario(21,'Customer repeats wrong information','Clarity + trust','A customer confidently states something about policy that is incorrect and says a friend received that treatment.','Acknowledge why they expected that outcome, explain the verified rule in plain language, and focus on the valid options available now.','Tell them their friend must be lying.','Say policies change all the time without checking the current rule.','Agree with their version to avoid conflict and process the unsupported outcome.','It corrects the misunderstanding without attacking the customer or abandoning the valid options.'),
  scenario(22,'Accessibility need','Inclusion + customer effort','A customer says they have difficulty reading a long set of instructions.','Adapt the explanation into short steps, confirm each step, and use supported accessibility or alternate-contact options when available.','Send the same instructions again with more detail.','Tell them to ask a family member to help.','Skip required verification steps because the process is difficult for them.','It reduces unnecessary effort while preserving required controls.'),
  scenario(23,'You made an error','Ownership + recovery','You realize you gave the customer incorrect information earlier in the same contact.','Correct it promptly, own the mistake without excuses, explain the accurate next step, and repair any avoidable impact if possible.','Quietly change your answer without mentioning the earlier error.','Blame the knowledge tool for giving you outdated information.','Continue with the original answer to avoid confusing the customer.','It protects trust by correcting the record quickly and taking responsibility for the impact.'),
  scenario(24,'Issue belongs to another team','Handoff quality','A customer needs a specialist team that you cannot replace, but they have already been transferred twice.','Explain why the specialist is needed, document the context, use the warmest supported handoff, and tell the customer what to expect next.','Transfer them immediately to save time.','Ask the customer to call a different number and start over.','Keep the case even though you lack the tools to resolve it.','It makes the necessary handoff useful instead of simply moving the customer again.'),
  scenario(25,'Multiple possible causes','Dive deep + diagnosis','A customer reports an intermittent technical issue that could have several causes.','Ask focused diagnostic questions, check the highest-probability or highest-risk causes first, and avoid changing multiple variables at once.','Try several fixes at the same time to maximize the chance that one works.','Assume the most common cause and give one generic fix.','Tell the customer intermittent issues cannot be diagnosed.','It narrows the problem systematically and preserves the ability to learn which action changed the outcome.'),
  scenario(26,'Policy exception request with hardship','Empathy + boundaries','A customer describes a genuine hardship and asks for an exception beyond your authority.','Acknowledge the hardship, explain what you can and cannot authorize, gather the facts needed for the proper exception/escalation path, and set expectations.','Grant the exception yourself because the situation sounds genuine.','Repeat the policy without acknowledging the hardship.','Promise a manager will approve it before escalating.','It combines empathy with honest authority boundaries and a practical escalation path.'),
  scenario(27,'Customer wants immediate answer but facts are missing','Accuracy + speed','A customer is in a hurry and asks you to decide before you can verify an important detail.','Explain the specific detail you must verify, gather it as efficiently as possible, and avoid a guess that could create a larger problem.','Give your best guess and correct it later if necessary.','Ask many unrelated verification questions just to be thorough.','Refuse to help until the customer has more time.','It protects accuracy while keeping verification focused and efficient.'),
  scenario(28,'Repeat process failure','Continuous improvement','You notice the same customer complaint appears repeatedly because an internal instruction is confusing.','Resolve the current case, document the pattern with evidence, and submit it through the appropriate improvement channel.','Fix only the current customer because process design is not your job.','Tell customers to ignore the confusing instruction.','Change the official instruction yourself without review.','It handles the immediate need and surfaces a repeatable improvement without bypassing controls.'),
  scenario(29,'Customer asks for private account info','Privacy + verification','Someone contacting support asks for detailed information about an account but cannot complete verification.','Do not disclose protected details, explain what verification is required, and offer any safe general guidance or recovery path available.','Share only part of the account information because it seems harmless.','Tell them which verification answer they need to provide.','Disclose the details because they know the order number.','It protects private information while still giving the person a safe next step.'),
  scenario(30,'End-of-contact closure','Follow-through','You believe the issue is resolved and the customer sounds satisfied. What is the best way to close?','Briefly recap what was done, confirm any remaining next step or timeline, check whether the main issue is resolved, and close clearly.','End the contact immediately once the action is complete.','Repeat the entire conversation from the beginning.','Promise there will definitely be no further issue.','It closes the loop, reduces uncertainty and avoids unsupported guarantees.'),
]

export const workStyleItems: WorkStyleItem[] = [...baseWorkStyleItems, ...extraWorkStyleItems]

const INCLUDED_SCENARIO_IDS = new Set([
  'sj-1', 'sj-2', 'sj-4', 'sj-5', 'sj-6', 'sj-7', 'sj-8', 'sj-9',
  'sj-10', 'sj-11', 'sj-12', 'sj-13', 'sj-14', 'sj-16', 'sj-17', 'sj-18',
  'sj-20', 'sj-21', 'sj-22', 'sj-23', 'sj-24', 'sj-27', 'sj-28', 'sj-30',
])

export const scenarioItems: ScenarioItem[] = [...baseScenarioItems.filter(item => INCLUDED_SCENARIO_IDS.has(item.id)), ...extraScenarioItems]

function shuffle<T>(items: readonly T[]): T[] {
  const result = [...items]
  for (let index = result.length - 1; index > 0; index -= 1) {
    const swapIndex = Math.floor(Math.random() * (index + 1))
    ;[result[index], result[swapIndex]] = [result[swapIndex], result[index]]
  }
  return result
}

export function createScenarioMock(count: number, excludeIds: string[] = []): ScenarioItem[] {
  const excluded = new Set(excludeIds)
  const available = scenarioItems.filter(item => !excluded.has(item.id))
  return shuffle(available).slice(0, Math.min(count, available.length)).map(item => ({
    ...item,
    options: shuffle(item.options).map((option, index) => ({ ...option, id: String.fromCharCode(97 + index) })),
  }))
}

export function createWorkStyleMock(count: number, excludeIds: string[] = []): WorkStyleItem[] {
  const excluded = new Set(excludeIds)
  const available = workStyleItems.filter(item => !excluded.has(item.id))
  return shuffle(available).slice(0, Math.min(count, available.length))
}
