import type { Question } from './questions'

type Seed = [Question['category'], Question['competency'], Question['difficulty'], string, string, string, string]
/** Original practice prompts. These are not official or recalled assessment items. */
const seeds: Seed[] = [
  ['customer-service','dive-deep','hard','Refund vs authorization','A customer says they were charged twice. One entry is pending and one is posted. Explain how you would investigate and what you would say before promising a refund.','Compare payment states with order records; do not assume both entries are settled charges.','What changes if both charges are posted?'],
  ['customer-service','ownership','hard','Return pickup never arrives','A return pickup has failed twice, and the customer has taken time off work each time. Respond to the customer and explain your next actions.','Name the practical impact, check failed attempts, and offer a supported next step with a follow-up condition.','How would you avoid making a third unreliable promise?'],
  ['customer-service','trust','hard','Conflicting refund advice','The previous agent promised an immediate refund, but you cannot verify that promise in the case notes. How would you handle the conversation?','Acknowledge the earlier expectation; check records and authority before correcting the timeline.','What would you document for the next agent?'],
  ['customer-service','empathy','medium','Replacement misses an occasion','A replacement will arrive after the birthday it was intended for. The customer says the replacement is now useless. Respond without inventing compensation policy.','Recognize why timing mattered, check available choices, and let the customer choose a valid option.','How would you respond if none of the options suited them?'],
  ['customer-service','communication','medium','Customer struggles with instructions','A customer says your troubleshooting steps are confusing and asks you to slow down. Show how you would explain the next step.','Use one action at a time, describe what they should see, and check understanding respectfully.','How would you adapt if they could not use the suggested channel?'],
  ['customer-service','dive-deep','hard','Delivery photo is unfamiliar','The order is marked delivered, but the customer does not recognize the location in the delivery photo. What would you verify before deciding the next step?','Separate tracking evidence from assumptions; use the supported delivery investigation process.','What if the customer needs the item urgently?'],
  ['customer-service','standards','hard','Damaged battery item','A customer reports a damaged battery-powered item that feels hot. What is your first response and how would you handle a return request?','Prioritize safety, use the applicable product safety guidance, and avoid ordinary return advice that may be unsafe.','Who needs to receive the incident details?'],
  ['customer-service','trust','hard','Account recovery for a relative','Someone wants you to recover their parent’s account and offers their own identity documents. How would you help?','Clarify account ownership and follow the approved recovery route without disclosing protected details.','What general help can you provide without verification?'],
  ['customer-service','dive-deep','medium','Refund to an old payment method','The customer has closed the card used for an order and asks where the refund will go. Explain what you would check and communicate.','Verify payment and refund records; do not promise to redirect funds without an authorized method.','What can you do if the customer’s bank cannot locate the refund?'],
  ['customer-service','ownership','medium','Chat disconnects during resolution','Your chat disconnects just after you submit a corrective action. What should your case notes and follow-through include?','Record the actual action status, unresolved questions and next step; follow supported recontact rules.','How would another agent know what is still pending?'],
  ['customer-service','communication','hard','Two issues in one contact','A customer describes a missing item and an unrelated subscription charge at the same time. Open the conversation and organize the work.','Briefly confirm both issues, agree on an order, and avoid losing the second issue while solving the first.','What if one issue requires another team?'],
  ['customer-service','trust','medium','Unknown delivery date','A customer demands an exact arrival date when tracking has no updated estimate. Give a useful response without guessing.','Explain what is known, what needs checking and when the next action can happen.','What if the customer says “I don’t want another vague answer”?'],
  ['customer-service','empathy','hard','Repeated subscription charge','A customer says they cancelled a subscription but were billed again. They are angry and worried about another charge. Respond and investigate.','Check cancellation and billing dates, clarify the concern, and verify both the existing charge and future billing state.','How would you confirm the customer understands the next step?'],
  ['customer-service','standards','medium','Incorrect address after dispatch','A customer entered the wrong address and asks you to change it after dispatch. What would you say and check?','Check supported delivery changes and safe alternatives; do not guarantee a reroute.','How would you avoid making the customer feel blamed?'],
  ['customer-service','communication','medium','Write a clear case summary','Write a short internal handoff note for a late order: customer contacted twice, tracking stalled, replacement eligibility not yet checked.','Separate verified facts, actions taken and the open decision.','What information should you leave out of a routine note?'],
  ['customer-service','results','hard','Queue speed and case quality','Your queue is growing while a complicated customer case needs investigation. Explain how you would balance both responsibilities.','Identify what can safely wait, preserve required checks and surface capacity risk early.','How would you measure whether your approach helped?'],
  ['behavioral','ownership','medium','Small mistake, real recovery','Tell me about a time you noticed a mistake you had made before someone complained. What did you do?','A study, family or business example is valid. Explain your own correction and observable result.','What changed in your process afterward?'],
  ['behavioral','trust','hard','Disagree without damaging trust','Describe a disagreement where you had evidence but the other person had more experience. How did you respond?','Show the evidence, respectful disagreement and what happened after the decision.','What would you do if the final decision still differed from yours?'],
  ['behavioral','curiosity','easy','Learn a tool from scratch','Describe how you learned an unfamiliar tool or process without someone guiding every step.','Use a specific example and explain how you checked your understanding.','When did you decide to ask for help?'],
  ['behavioral','standards','hard','Catch an error in a rush','Tell me about a time you caught an error while others were trying to finish quickly.','Describe the risk and your practical response without exaggerating its scale.','How did you keep the work moving?'],
  ['behavioral','results','medium','Prioritize conflicting deadlines','Describe a time you had two deadlines you could not both meet as originally planned.','Explain the priorities, what you communicated, and what actually happened.','What did you learn about setting expectations?'],
  ['behavioral','empathy','easy','Help someone learn','Tell me about a time you explained something to a person who was struggling to understand it.','Show how you changed your explanation based on their needs.','How did you check that it worked?'],
  ['behavioral','dive-deep','hard','Wrong first assumption','Describe a problem where your first explanation turned out to be wrong.','Explain what evidence changed your mind and how you corrected the approach.','What would you check earlier next time?'],
  ['behavioral','ownership','medium','No one assigned the task','Tell me about a useful task you completed even though no one specifically assigned it to you.','Explain why it mattered, your boundaries, and the result without claiming all the credit.','How did you decide it was appropriate to act?'],
  ['behavioral','trust','medium','Difficult feedback','Describe feedback that was uncomfortable to hear but helped you improve.','Name the feedback and one concrete behavior you changed.','How do you know the improvement lasted?'],
  ['behavioral','communication','medium','Explain a delay honestly','Tell me about a time you had to explain a delay or disappointing outcome.','Describe what you knew, what you communicated and how the other person responded.','What expectation would you set differently today?'],
  ['behavioral','standards','hard','Simplify without skipping checks','Describe a time you made a repetitive task simpler without reducing its quality.','Explain the repeated friction, your change and a way you checked the result.','Which step was important to retain?'],
  ['behavioral','results','easy','A setback you worked through','Tell me about a goal that took longer than expected and how you responded to the setback.','Use a truthful example; give your adjustment and actual outcome, even if imperfect.','What did the setback teach you?'],
  ['amazon-style','communication','easy','Honest shift availability','How would you discuss your availability for rotating shifts if you had a genuine scheduling constraint?','State what you can do and what you cannot commit to; avoid promises you cannot keep.','How would you ask for clarification about the schedule?'],
  ['amazon-style','curiosity','medium','First week in support','What would you focus on learning in your first week as a customer service associate?','Choose a few practical priorities: tools, support boundaries, knowledge sources and asking for help.','How would you know you were ready for more independent work?'],
  ['amazon-style','trust','medium','Quality feedback vs speed','A reviewer says your answer was accurate but difficult for the customer to follow. How would you improve?','Treat clarity as part of quality; give a concrete change to your explanation.','How could you check improvement beyond handling time?'],
  ['amazon-style','ownership','hard','No answer in the knowledge base','You cannot find a clear answer in the approved knowledge resource. What do you do while the customer waits?','Explain the specific uncertainty, use the appropriate help route and avoid filling the gap with a guess.','What would you include when asking a specialist for help?'],
  ['extempore','communication','easy','Teach a simple everyday skill','Explain how to do a simple everyday task to someone trying it for the first time.','Use a short introduction, numbered steps and one practical tip.','Which step is easiest to misunderstand?'],
  ['extempore','communication','easy','A place in your city','Describe a place in your city you would recommend to a visitor and explain why.','Use two concrete details and consider what the visitor would enjoy.','Who might prefer a different place?'],
  ['extempore','communication','medium','Convenience and personal service','Do you prefer self-service tools or speaking to a person when you need help? Explain with an example.','Give a position, a real example and one situation where the other option works better.','What makes a self-service tool frustrating?'],
  ['extempore','communication','medium','A useful habit','Describe one habit that made your daily life easier and how you developed it.','Explain the problem, the habit and a realistic benefit.','What helps you maintain it on a difficult day?'],
  ['extempore','communication','hard','When speed is not enough','Speak for about a minute on why solving a problem quickly is not always the same as solving it well.','Develop two distinct points and one ordinary example; avoid repeating the title.','When does speed itself become important?'],
  ['extempore','communication','medium','Describe a product clearly','Choose an everyday product and explain its purpose, one useful feature and one limitation to a new user.','Use plain language and an honest limitation rather than sales language.','How would you explain it to someone less comfortable with technology?'],
  ['extempore','communication','easy','A recent small win','Talk about a small thing you accomplished recently and why it mattered to you.','Keep the scale truthful; use past tense and specific detail.','What made it harder than expected?'],
  ['extempore','communication','hard','A respectful different opinion','Explain an everyday topic on which reasonable people can disagree, and present both views before your own conclusion.','Represent both views fairly and use clear transitions.','What evidence might change your conclusion?'],
]

export const expandedQuestions: Question[] = seeds.map(([category, competency, difficulty, title, prompt, hint, followUp], index) => {
  const rubric = category === 'customer-service'
    ? ['Recognizes the customer’s practical concern', 'Verifies relevant facts before deciding', 'Chooses a supported action without guessing policy', 'Sets honest expectations and a next step', 'Communicates with calm ownership']
    : category === 'behavioral'
      ? ['Uses one truthful and specific example', 'Explains enough context to understand the decision', 'Makes personal actions and reasoning clear', 'Describes an observable outcome', 'Reflects on a relevant lesson']
      : ['Answers the exact prompt directly', 'Develops distinct points with useful details', 'Uses natural, clear English', 'Keeps claims truthful and realistic', 'Finishes with a clear final point']
  return { id: `expanded-${String(index + 1).padStart(2, '0')}`, category, competency, difficulty, title, prompt, hint, followUp, rubric, idealCharacteristics: rubric, type: category === 'behavioral' ? 'workstyle' : category === 'customer-service' ? 'scenario' : 'extempore', context: 'Original CSA preparation material. Use your own facts and examples; actual hiring formats can vary.', commonMistakes: category === 'customer-service' ? ['Promising an unverified outcome', 'Acting before checking the relevant facts', 'Blaming the customer or another agent'] : ['Using a memorized answer unrelated to the prompt', 'Inventing experience or results', 'Repeating a point without developing it'] }
})
